### ISSUE TITLE
OpenAPI schema checks for other use_cases than :read

### ISSUE THREAD

**Issue by ans-ioki** [ioki-mobility/ioki-ruby#19]

**Comment by A5308Y** [comment]
I had another look at this and it's not easy to do, because in the cases where an attribute is defined for `:create` or `:update`, but not for `:read` it's usually a slight difference in what is sent and what's returned. Like a foreign-key `id` for an association or a `terms_accepted` boolean instead of a `terms_accepted_at` timestamp.

In these cases the API definition is not referencing a predefined schema and is defining a custom object for these endpoints instead. Reading these is quite a bit of yml-navigating, that's probably not worth the effort.
